services:
  openui:
    container_name: openui
    image: ghcr.io/wandb/openui:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    env_file:
      - .env
